### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by wesleygauntt** [raven-bootcamp/week4-homework-quiz#1]
Hey -- this is awesome! I didn't see a spot for feedback, so here's an issue instead.

There's a lot of cool functionality here! Using `localStorage`, client-side rendering + basically your own state engine. Good stuff!

I think for feedback, I'd recommend code splitting. Instead of `script.js`, consider `timer.js`, `scoreboard.js`, `gameManager.js`, etc. 

A few patterns that have worked for me:

```js
// questions.js
export const questions = [
  // {},{},{},{}
]
```

```js
// timer.js
export class Timer {
  constructor(gamelength) {
    this.gamelength = gamelength;
  }

  startClock() {
    // ...
  }

  verifyTime() {
    // ...
    if(totalTime <= 0) {
      document.dispatchEvent(new Event('timeup'));
    }
  }
}
```

```js
// gameManager.js
import { questions } from './data.js';
import { Timer } from './timer.js';

window.onload = function () {
  // ...
  shuffledQuestions = questions.sort();

  const timer = new Timer(75);
  timer.startClock();

  // ...
  document.addEventListener('timeup', function(){
    console.log("Game over!");
  })
}
```

```html
// index.html
// ...
<script src="./gameManager.js" type="module"></script>
```

For local development, you will probably get a CORS error attempting the above. This is easy to get around if you have have npm installed. Globally install [npx](https://www.npmjs.com/package/npx) `npm install -g npx` & inside of your working directory run `npx http-server . -p=3000`. 

This will set up a remote instance of [http-server](https://www.npmjs.com/package/http-server), and you can check your work at localhost:3000. Browsers are picky about `js` reading files.

.

Anyway I got one question wrong on the quiz, so take this all with a grain of salt I guess.

Fun game, and I'm looking foward to seeing more!

**Comment by raven-bootcamp** [comment]
Hey @wesleygauntt , so kind of you to offer feedback, thanks so much!  😁 

I definitely see your point about splitting up all the JS into smaller, more manageable chunks, but I'm afraid it's a bit beyond the scope of what we've learned so far.  I'll stick to the pace and level of the curriculum for now, but will definitely keep it in mind for future projects!

I've had a few people say they got a question or two wrong, so you're not alone there 😉 

Thanks again.
